### ISSUE TITLE
GoldSrc MDL V4 and V6 cannot import into Blender v4.1, w/ SourceIO v5.3.0

### ISSUE THREAD

**Issue by Teajai2** [REDxEYE/SourceIO#281]
MDL versions 4 and 6 no longer import on Blender v4.1, using the **SourceIO v5.3.0 plugin**. Regular GoldSrc models still import fine.

While fixing this would understandably not be a high priority, given the limited uses for importing v4 and v6 models, importing these files would still be a nice luxury to have given that this is currently the only method of converting v4 models into any kind of decompilable format.

### MDL v4 error code when trying to open  the 0.52 Half-Life 1 prototype's "hsarge.mdl":
Python: Traceback (most recent call last):
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 51, in execute
    model_container = import_model(mdl_path, f, content_manager, self, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\__init__.py", line 30, in import_model
    container = handler(model_path, buffer, content_manager, options)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl4\__init__.py", line 14, in import_mdl4
    return import_model(model_path.stem, buffer, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl4\import_mdl.py", line 71, in import_model
    mdl = Mdl.from_buffer(mdl_buffer)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\library\models\mdl\v4\mdl_file.py", line 40, in from_buffer
    assert total_model_count == header.unk_count, \
                                ^^^^^^^^^^^^^^^^
AttributeError: 'StudioHeader' object has no attribute 'unk_count'. Did you mean: 'bone_count'?_

### MDL v6 error code when trying to open  the 0.52 Half-Life 1 prototype's "hgrunt.mdl":
_Python: Traceback (most recent call last):
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 51, in execute
    model_container = import_model(mdl_path, f, content_manager, self, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\__init__.py", line 30, in import_model
    container = handler(model_path, buffer, content_manager, options)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl6\__init__.py", line 17, in import_mdl6
    return import_model(buffer, texture_mdl, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl6\import_mdl.py", line 66, in import_model
    mdl = Mdl.from_buffer(mdl_file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\library\models\mdl\v6\mdl_file.py", line 26, in from_buffer
    header = StudioHeader.from_buffer(buffer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\library\models\mdl\v6\structs\studioheader.py", line 60, in from_buffer
    return cls(version, name, file_size, *hdr_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StudioHeader.__init__() missing 2 required positional arguments: 'body_part_count' and 'body_part_offset'_

**Comment by REDxEYE** [comment]
Should be fixed by 14742958

**Comment by REDxEYE** [comment]
Please test and close issue if resolved

**Comment by Teajai2** [comment]
I tested commit [1474295](https://github.com/REDxEYE/SourceIO/commit/147429586a1bbd0f5693e782b30f7461aeb50b11). Unfortunately, the issue has not been resolved yet.

### MDL v4 Import Error Code w/ hsarge.mdl
```
Python: Traceback (most recent call last):
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 53, in execute
    model_container = import_model(mdl_path, f, content_manager, self, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\__init__.py", line 30, in import_model
    container = handler(model_path, buffer, content_manager, options)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl4\__init__.py", line 14, in import_mdl4
    return import_model(model_path.stem, buffer, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl4\import_mdl.py", line 90, in import_model
    model_vertices = model.vertices * options.scale
                     ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
numpy.core._exceptions._UFuncNoLoopError: ufunc 'multiply' did not contain a loop with signature matching types (dtype([('id', '<u4', (1,)), ('pos', '<f4', (3,))]), dtype('float64')) -> None
```

### MDL v6 Import Error Code w/ hgrunt.mdl
```
Python: Traceback (most recent call last):
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 53, in execute
    model_container = import_model(mdl_path, f, content_manager, self, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\__init__.py", line 30, in import_model
    container = handler(model_path, buffer, content_manager, options)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl4\__init__.py", line 14, in import_mdl4
    return import_model(model_path.stem, buffer, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl4\import_mdl.py", line 90, in import_model
    model_vertices = model.vertices * options.scale
                     ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
numpy.core._exceptions._UFuncNoLoopError: ufunc 'multiply' did not contain a loop with signature matching types (dtype([('id', '<u4', (1,)), ('pos', '<f4', (3,))]), dtype('float64')) -> None

```

**Comment by Teajai2** [comment]
Tried c1f9af3, still does not work.
### Error code for MDL V6, hgrunt.mdl
```
Python: Traceback (most recent call last):
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 53, in execute
    model_container = import_model(mdl_path, f, content_manager, self, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\__init__.py", line 30, in import_model
    container = handler(model_path, buffer, content_manager, options)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl6\__init__.py", line 17, in import_mdl6
    return import_model(buffer, texture_mdl, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl6\import_mdl.py", line 66, in import_model
    mdl = Mdl.from_buffer(mdl_file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\library\models\mdl\v6\mdl_file.py", line 30, in from_buffer
    sequences = buffer.read_structure_array(header.sequence_offset, header.sequence_count, StudioSequence)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\library\utils\file_utils.py", line 208, in read_structure_array
    obj = data_class.from_buffer(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\library\models\mdl\v6\structs\sequence.py", line 37, in from_buffer
    ) = buffer.read_fmt('<fI9I')
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\library\utils\file_utils.py", line 70, in read_fmt
    return unpack(self._endian + fmt, self.read(calcsize(self._endian + fmt)))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: bad char in struct format
```

### Error code for MDL v4, hsarge.mdl
```
Python: Traceback (most recent call last):
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 53, in execute
    model_container = import_model(mdl_path, f, content_manager, self, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\__init__.py", line 30, in import_model
    container = handler(model_path, buffer, content_manager, options)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl4\__init__.py", line 14, in import_mdl4
    return import_model(model_path.stem, buffer, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl4\import_mdl.py", line 119, in import_model
    remap[model_material_index] = load_material(model_name, model_material_index, model_texture_info,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl4\import_mdl.py", line 153, in load_material
    bpy_material.create_nodes(material)
  File "C:\Users\orion\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\material_loader\shaders\goldsrc_shaders\goldsrc_shader.py", line 29, in create_nodes
    if self._valve_material.flags & MdlTextureFlag.CHROME:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StudioTexture' object has no attribute 'flags'
```

**Comment by REDxEYE** [comment]
Try now

**Comment by Teajai2** [comment]
Same error messages as before. Interestingly, I took a look at some older versions of the addon and found that they also can't import these older MDL files into the newest version of Blender anymore — it only imports their skeletons.

### MDL V6
```
Python: Traceback (most recent call last):
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 53, in execute
    model_container = import_model(mdl_path, f, content_manager, self, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\__init__.py", line 30, in import_model
    container = handler(model_path, buffer, content_manager, options)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl6\__init__.py", line 17, in import_mdl6
    return import_model(buffer, texture_mdl, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl6\import_mdl.py", line 66, in import_model
    mdl = Mdl.from_buffer(mdl_file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\library\models\mdl\v6\mdl_file.py", line 30, in from_buffer
    sequences = buffer.read_structure_array(header.sequence_offset, header.sequence_count, StudioSequence)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\library\utils\file_utils.py", line 208, in read_structure_array
    obj = data_class.from_buffer(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\library\models\mdl\v6\structs\sequence.py", line 37, in from_buffer
    ) = buffer.read_fmt('<fI9I')
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\library\utils\file_utils.py", line 70, in read_fmt
    return unpack(self._endian + fmt, self.read(calcsize(self._endian + fmt)))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: bad char in struct format
```

### MDL V4
```
Python: Traceback (most recent call last):
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 53, in execute
    model_container = import_model(mdl_path, f, content_manager, self, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\__init__.py", line 30, in import_model
    container = handler(model_path, buffer, content_manager, options)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl4\__init__.py", line 14, in import_mdl4
    return import_model(model_path.stem, buffer, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl4\import_mdl.py", line 119, in import_model
    remap[model_material_index] = load_material(model_name, model_material_index, model_texture_info,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\models\mdl4\import_mdl.py", line 153, in load_material
    bpy_material.create_nodes(material)
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\material_loader\shaders\goldsrc_shaders\goldsrc_shader.py", line 29, in create_nodes
    if self._valve_material.flags & MdlTextureFlag.CHROME:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StudioTexture' object has no attribute 'flags'
```

**Comment by REDxEYE** [comment]
Can you just drop me mdl v4 and v6 so I can test locally?

**Comment by Teajai2** [comment]
Sure thing, here you go.
[0.52 Alpha Models.zip](https://github.com/REDxEYE/SourceIO/files/15181947/0.52.Alpha.Models.zip)

**Comment by REDxEYE** [comment]
4cdd1d6 should fix your issues
